{{- if .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-prometheus-analyzer.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.exporter.serviceMonitor.namespace | quote }}
  labels:
    {{- include "k8s-prometheus-analyzer.labels" . | nindent 4 }}
    {{- with .Values.exporter.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-prometheus-analyzer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      interval: {{ default "30s" .Values.exporter.serviceMonitor.interval }}
      honorLabels: true
      {{- with .Values.exporter.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
